[build]
    command = netlify.toml && CI= npm run build"

# API proxying
[[redirects]]
    from = "/api/*"
    to = "https://food-web-server.herokuapp.com/api:splat"
    status = 200
    force = true

# React Router support
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200